/**
 * @fileoverview Disincentivizes some coding practices.
 * @author Bleacher Report
 */
"use strict";

//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

var requireIndex = require("requireindex");

//------------------------------------------------------------------------------
// Plugin Definition
//------------------------------------------------------------------------------


// import all rules in lib/rules
module.exports = {
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "arrowFunctions": true,
      "binaryLiterals": true,
      "blockBindings": true,
      "classes": true,
      "defaultParams": true,
      "destructuring": true,
      "experimentalObjectRestSpread": true,
      "forOf": true,
      "generators": true,
      "globalReturn": false,
      "jsx": true,
      "modules": true,
      "objectLiteralComputedProperties": true,
      "objectLiteralDuplicateProperties": true,
      "objectLiteralShorthandMethods": true,
      "objectLiteralShorthandProperties": true,
      "octalLiterals": true,
      "regexUFlag": true,
      "regexYFlag": true,
      "restParams": true,
      "spread": true,
      "superInFunctions": true,
      "templateStrings": true,
      "unicodeCodePointEscapes": true
    },
    "sourceType": "module"
  },
  plugins: [
    "react",
    "babel"
  ],
  rules: requireIndex(__dirname + "/rules"),
  configs: {
    recommended: {
      rules: {
        "@br/laws-of-the-game/alphabetize-properties": "error",
        "@br/laws-of-the-game/no-assign-in-case-without-braces": "error",
        "@br/laws-of-the-game/no-unauthorized-global-properties": "error",
        "@br/laws-of-the-game/no-use-entire-process-dot-env": "error",
        "@br/laws-of-the-game/prefer-includes-over-indexof": "error",
        "accessor-pairs" : "error",
        "arrow-parens" : ["error","always"],
        "arrow-spacing" : "error",
        "block-scoped-var" : "warn",
        "block-spacing" : "error",
        "brace-style" : "error",
        "callback-return" : "off",
        "comma-dangle" : ["error", "never"],
        "comma-spacing" : ["error", {"after" : true, "before" : false}],
        "comma-style" : ["error", "last"],
        "complexity" : "off",
        "computed-property-spacing" : ["error", "never"],
        "consistent-return" : "error",
        "constructor-super" : "error",
        "curly" : "error",
        "default-case" : "error",
        "eol-last" : "error",
        "eqeqeq" : [ "error", "smart" ],
        "generator-star-spacing" : ["error", {"after" : true, "before" : true}],
        "guard-for-in" : "error",
        "handle-callback-err" : "warn",
        "id-length" : ["error", {"max" : 32, "min" : 2, "properties" : "never"}],
        "jsx-quotes": ["error", "prefer-double"],
        "keyword-spacing" : ["error", {"after" : true, "before" : true, "overrides" : {}}],
        "new-cap" : "error",
        "no-alert" : "error",
        "no-array-constructor" : "error",
        "no-caller" : "error",
        "no-catch-shadow" : "off",
        "no-class-assign" : "error",
        "no-cond-assign" : [ "error", "except-parens"],
        "no-console" : "error",
        "no-const-assign" : "error",
        "no-constant-condition" : "error",
        "no-control-regex" : "warn",
        "no-debugger" : "error",
        "no-delete-var" : "error",
        "no-div-regex" : "error",
        "no-dupe-args" : "error",
        "no-dupe-class-members" : "error",
        "no-dupe-keys" : "error",
        "no-duplicate-case" : "error",
        "no-else-return" : "error",
        "no-empty" : "error",
        "no-empty-character-class" : "warn",
        "no-eq-null" : "error",
        "no-eval" : "error",
        "no-ex-assign" : "error",
        "no-extend-native" : "warn",
        "no-extra-bind" : "error",
        "no-extra-boolean-cast" : "error",
        "no-extra-parens" : "error",
        "no-extra-semi" : "error",
        "no-floating-decimal" : "error",
        "no-func-assign" : "error",
        "no-implied-eval" : "error",
        "no-inner-declarations" : "error",
        "no-invalid-regexp" : "error",
        "no-irregular-whitespace" : "error",
        "no-iterator" : "error",
        "no-label-var" : "error",
        "no-labels" : "error",
        "no-lone-blocks" : "error",
        "no-lonely-if" : "error",
        "no-loop-func" : "error",
        "no-mixed-spaces-and-tabs" : "error",
        "no-multi-spaces" : "error",
        "no-multi-str" : "error",
        "no-multiple-empty-lines" : "error",
        "no-native-reassign" : "error",
        "no-negated-in-lhs" : "error",
        "no-new" : "error",
        "no-new-func" : "error",
        "no-new-object" : "error",
        "no-new-require" : "warn",
        "no-obj-calls" : "error",
        "no-octal" : "error",
        "no-octal-escape" : "error",
        "no-param-reassign" : "error",
        "no-path-concat" : "warn",
        "no-process-env" : "off",
        "no-process-exit" : "warn",
        "no-proto" : "error",
        "no-redeclare" : "error",
        "no-regex-spaces" : "warn",
        "no-return-assign" : "off",
        "no-script-url" : "error",
        "no-self-compare" : "error",
        "no-shadow-restricted-names" : "error",
        "no-spaced-func" : "error",
        "no-sparse-arrays" : "error",
        "no-this-before-super" : "error",
        "no-trailing-spaces" : "error",
        "no-undef" : "error",
        "no-undef-init" : "error",
        "no-unexpected-multiline" : "error",
        "no-unneeded-ternary" : "error",
        "no-unreachable" : "error",
        "no-use-before-define" : "error",
        "no-useless-call" : "error",
        "no-useless-concat" : "error",
        "no-var" : "warn",
        "no-void" : "error",
        "no-with" : "warn",
        "object-curly-spacing" : "off",
        "object-shorthand" : "warn",
        "padded-blocks" : ["warn", "never"],
        "prefer-const": "error",
        "prefer-spread" : "warn",
        "prefer-template" : "warn",
        "quotes" : ["warn", "double"],
        "radix" : "off",
        "react/display-name" : "off",
        "react/forbid-component-props" : "off",
        "react/forbid-prop-types" : "warn",
        "react/jsx-boolean-value" : ["warn", "always"],
        "react/jsx-closing-bracket-location" : "off",
        "react/jsx-curly-spacing" : ["warn", "never"],
        "react/jsx-equals-spacing" : ["error", "never"],
        "react/jsx-filename-extension" : "off",
        "react/jsx-first-prop-new-line" : ["error", "multiline"],
        "react/jsx-handler-names" : "off",
        "react/jsx-indent" : "off",
        "react/jsx-key" : "warn",
        "react/jsx-max-props-per-line" : ["warn", {"maximum" : 3 }],
        "react/jsx-no-bind" : ["warn", {"allowArrowFunctions" : false, "allowBind" : false, "ignoreRefs" : true}],
        "react/jsx-no-comment-textnodes" : "error",
        "react/jsx-no-duplicate-props" : "warn",
        "react/jsx-no-literals" : "off",
        "react/jsx-no-target-blank" : "error",
        "react/jsx-no-undef" : "warn",
        "react/jsx-pascal-case" : ["error", {"allowAllCaps" : true }],
        "react/jsx-sort-props" : "off",
        "react/jsx-space-before-closing" : "off",
        "react/jsx-uses-react" : "warn",
        "react/jsx-uses-vars" : "warn",
        "react/jsx-wrap-multilines" : "off",
        "react/no-danger" : "off",
        "react/no-danger-with-children" : "error",
        "react/no-deprecated" : "warn",
        "react/no-did-update-set-state" : "error",
        "react/no-direct-mutation-state" : "error",
        "react/no-is-mounted" : "error",
        "react/no-multi-comp" : ["error", {"ignoreStateless" : true }],
        "react/no-render-return-value" : "error",
        "react/no-set-state" : "off",
        "react/no-string-refs" : "error",
        "react/no-unescaped-entities" : "off",
        "react/no-unknown-property" : "error",
        "react/no-unused-prop-types" : "warn",
        "react/prefer-es6-class" : ["error", "always"],
        "react/prefer-stateless-function" : ["warn", { "ignorePureComponents": true}],
        "react/prop-types" : "off",
        "react/react-in-jsx-scope" : "error",
        "react/require-optimization" : "warn",
        "react/require-render-return" : "error",
        "react/self-closing-comp" : "warn",
        "react/sort-prop-types" : "warn",
        "react/style-prop-object" : "error",
        "require-yield" : "error",
        "semi" : ["error", "always"],
        "space-before-function-paren" : ["error", {"anonymous": "never", "named": "never", "asyncArrow": "ignore"}],
        "space-infix-ops" : ["error", {"int32Hint" : false }],
        "space-unary-ops" : ["warn", {"nonwords" : false, "words" : true}],
        "use-isnan" : "error",
        "valid-typeof" : "error",
        "vars-on-top" : "warn",
        "wrap-iife" : "warn",
        "wrap-regex" : "warn"
      }
    }
  }
};
